name: Viruna-MD Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Bot
        run: |
          # Session ID එක පිරිසිදු කරලා දුවනවා
          CLEAN_SESSION=$(echo "${{ secrets.SESSION_ID }}" | sed "s/['\"]//g")
          SESSION_ID=$CLEAN_SESSION node index.js
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
