name: Viruna-MD Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        run: |
          node index.js & # Bot එක background එකේ run කරන්න
          sleep infinity # Workflow එක එකපාරටම ඉවර වෙන්න නොදී තියාගන්න
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
